#!/usr/bin/bash

state=$(upower -i $(upower -e | grep 'BAT') | grep -E "state" | awk '{print $NF}')
wp_vid=$(basename $(realpath ~/.wallpapers/.wallpaper.mp4))
wp_img=$(basename $(realpath ~/.wallpapers/.wallpaper.png))

rm ~/.wallpapers/.wallpaper.*

while [ True ]; do
  ls ~/.wallpapers/img/ | sort -R | head -n 1 | while read file; do 
    if [[ $file == $wp_img ]]; then break ; fi
    ln -s ~/.wallpapers/img/$file ~/.wallpapers/.wallpaper.png ; done
  if [[ -f ~/.wallpapers/.wallpaper.png ]]; then break; fi
done

while [ True ]; do
  ls ~/.wallpapers/vid/ | sort -R | head -n 1 | while read file; do 
    if [[ $file == $wp_vid ]]; then break ; fi
    ln -s ~/.wallpapers/vid/$file ~/.wallpapers/.wallpaper.mp4 ; done
  if [[ -f ~/.wallpapers/.wallpaper.mp4 ]]; then break; fi
done

feh --bg-scale ~/.wallpapers/.wallpaper.png

killall -9 xwinwrap

if [[ $1 == 'start' || ( ! $state == 'discharging' && ! $1 == 'stop' ) ]];
then
  xwinwrap -g 1366x768 -ov -- \
    mpv --profile=wallpaper -wid WID ~/.wallpapers/.wallpaper.mp4
fi

