vim.cmd("colorscheme kanagawa-paper")
vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number relativenumber")
vim.cmd("set colorcolumn=118")
vim.cmd("set textwidth=118")
vim.cmd("set cmdheight=0")
vim.cmd("set autoindent smartindent")
vim.cmd("syntax enable")
vim.cmd("filetype plugin indent on")
