#!/bin/bash

inet=`ip addr | grep 'inet' | awk '{print $2" "$9}'`

while IFS= read -r line;
do
  case `printf '%s\n' "$line" | awk '{print $2}'` in
    enp4s0)
      echo " enp4s0: `echo "$line" | awk '{print $1}' | rev | cut -c4- | rev` "
      ;;
    enp0s25)
      echo " enp0s25: `echo "$line" | awk '{print $1}' | rev | cut -c4- | rev` "
      ;;
    wlan0)
      echo " wlan0: `echo "$line" | awk '{print $1}' | rev | cut -c4- | rev` "
      ;;
  esac
done < <(printf '%s\n' "$inet")
